server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TerasoftSW/config-data.git
          username: ${TERASOFT_GIT_USER}
          password: ${TERASOFT_GIT_TOKEN}
          default-label: main
          searchPaths: servicesbc-service, userprofile-service, subscription-service
          cloneOnStart: true